In [6]:
import numpy as np
import matplotlib.pyplot as plt

In [7]:
a=[[11,12,13],[21,22,23],[31,32,33]]
a

[[11, 12, 13], [21, 22, 23], [31, 32, 33]]

In [8]:
# every element if of the same type
a=np.array(a)
a

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [10]:
a.ndim

2

In [12]:
a.shape

(3, 3)

In [13]:
a.size

9

In [15]:
a[1,2]

23

In [16]:
a[1][2]

23

In [18]:
a[0][0:2]

array([11, 12])

In [19]:
X=np.array([[1,0],[0,1]]) 
X

array([[1, 0],
       [0, 1]])

In [20]:
Y=np.array([[2,1],[1,2]]) 
Y

array([[2, 1],
       [1, 2]])

In [23]:
Z=X+Y
Z

array([[3, 1],
       [1, 3]])

In [25]:
Z=2*Y
Z

array([[4, 2],
       [2, 4]])

In [26]:
A=np.array([[0,1,1],[1,0,1]])
A

array([[0, 1, 1],
       [1, 0, 1]])

In [27]:
B=np.array([[1,1],[1,1],[-1,1]])
B

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [31]:
Z=np.dot(A,B)
Z

array([[0, 2],
       [0, 2]])

In [32]:
np.sin(Z)

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [33]:
C=np.array([[1,1],[2,2],[3,3]])
C

array([[1, 1],
       [2, 2],
       [3, 3]])

In [34]:
C.T

array([[1, 2, 3],
       [1, 2, 3]])